kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummy-role
rules:
- apiGroups: [""]
  resources: ["pods","configmaps"]
  verbs: ["get","list","create"]
- apiGroups: ["stable.dwk"]
  resources: ["dummysites"]
  verbs: ["get","list","watch"]
